import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/iptv_item.dart';

class XtreamSource { const XtreamSource({required this.server,required this.username,required this.password}); final String server,username,password; }
class IptvService {
  IptvService._(); static final instance=IptvService._(); final _client=http.Client();
  Future<List<IptvItem>> loadM3u(String url) async { final r=await _client.get(Uri.parse(url),headers:{'User-Agent':'IPTV-Lite/1.0'}).timeout(const Duration(minutes:3)); if(r.statusCode!=200) throw Exception('M3U HTTP ${r.statusCode}'); return parseM3u(r.body); }
  List<IptvItem> parseM3u(String body){ final out=<IptvItem>[]; String? name,logo,group; var headers=<String,String>{}; for(final raw in const LineSplitter().convert(body)){ final line=raw.trim(); if(line.isEmpty||line.startsWith('#EXTM3U'))continue; if(line.startsWith('#EXTINF:')){final comma=line.indexOf(','); final meta=comma>=0?line.substring(0,comma):line; name=comma>=0?line.substring(comma+1).trim():'Channel'; logo=_attr(meta,'tvg-logo'); group=_attr(meta,'group-title'); headers={}; continue;} if(line.startsWith('#EXTVLCOPT:')){final v=line.substring(11); final eq=v.indexOf('='); if(eq>0)headers[_header(v.substring(0,eq))]=v.substring(eq+1).trim(); continue;} if(line.startsWith('#'))continue; if(name!=null&&RegExp(r'^(https?|rtmp|rtsp|udp|mms)://',caseSensitive:false).hasMatch(line)){final parts=line.split('|'); final url=parts.first.trim(); if(parts.length>1){for(final p in parts.skip(1).join('|').split('&')){final eq=p.indexOf('='); if(eq>0)headers[_header(p.substring(0,eq))]=Uri.decodeComponent(p.substring(eq+1));}} out.add(IptvItem(name:name!,url:url,logo:logo,group:group,headers:Map.of(headers)));} name=null;logo=null;group=null;headers={}; } return out; }
  Future<List<IptvItem>> loadXtreamLive(XtreamSource s)=>_xtreamList(s,'get_live_streams',IptvKind.live);
  Future<List<IptvItem>> loadXtreamMovies(XtreamSource s)=>_xtreamList(s,'get_vod_streams',IptvKind.movie);
  Future<List<IptvItem>> loadXtreamSeries(XtreamSource s)=>_xtreamList(s,'get_series',IptvKind.series);
  Future<List<IptvItem>> _xtreamList(XtreamSource s,String action,IptvKind kind)async{final d=await _get(s,action); if(d is! List)return const []; return [for(final raw in d.whereType<Map>())_item(s,Map<String,dynamic>.from(raw),kind)];}
  Future<List<IptvItem>> loadSeriesEpisodes(XtreamSource s,String id)async{final d=await _get(s,'get_series_info',{'series_id':id}); final out=<IptvItem>[]; if(d is! Map||d['episodes'] is! Map)return out; for(final e in (d['episodes'] as Map).entries){final season=int.tryParse(e.key.toString())??0; if(e.value is! List)continue; for(final raw in (e.value as List).whereType<Map>()){final m=Map<String,dynamic>.from(raw); final eid=m['id']?.toString(); if(eid==null)continue; final n=int.tryParse(m['episode_num']?.toString()??'')??0; final ext=m['container_extension']?.toString()??'mp4'; final info=m['info'] is Map?Map<String,dynamic>.from(m['info']):const <String,dynamic>{}; out.add(IptvItem(name:'S${season.toString().padLeft(2,'0')}E${n.toString().padLeft(2,'0')} ${m['title']??''}'.trim(),url:'${_root(s)}/series/${Uri.encodeComponent(s.username)}/${Uri.encodeComponent(s.password)}/$eid.$ext',logo:info['movie_image']?.toString(),group:'Season $season',kind:IptvKind.series,id:eid,season:season,episode:n));}} return out;}
  Future<dynamic> _get(XtreamSource s,String action,[Map<String,String> extra=const{}])async{final q={'username':s.username,'password':s.password,'action':action,...extra}; final r=await _client.get(Uri.parse(_base(s)).replace(queryParameters:q),headers:{'User-Agent':'IPTV-Lite/1.0'}).timeout(const Duration(seconds:45)); if(r.statusCode!=200)throw Exception('Xtream HTTP ${r.statusCode}'); return jsonDecode(r.body);}
  String _base(XtreamSource s)=>'${_root(s)}/player_api.php'; String _root(XtreamSource s)=>s.server.replaceFirst(RegExp(r'/+$'),'');
  IptvItem _item(XtreamSource s,Map<String,dynamic> m,IptvKind k){final id=(m['stream_id']??m['series_id']??m['id']).toString(); final ext=m['container_extension']?.toString()??'mp4'; final type=k==IptvKind.live?'live':k==IptvKind.movie?'movie':'series'; final url=k==IptvKind.series?'${_root(s)}/series/${Uri.encodeComponent(s.username)}/${Uri.encodeComponent(s.password)}/$id.mp4':'${_root(s)}/$type/${Uri.encodeComponent(s.username)}/${Uri.encodeComponent(s.password)}/$id.${k==IptvKind.live?'m3u8':ext}'; return IptvItem(name:(m['name']??'Untitled').toString(),url:url,logo:(m['stream_icon']??m['cover'])?.toString(),group:m['category_name']?.toString(),kind:k,id:id);}
  static String? _attr(String s,String key){final m=RegExp('''$key=["']([^"']*)["']''',caseSensitive:false).firstMatch(s);return m?.group(1);}
  static String _header(String k){switch(k.toLowerCase().replaceAll('_','-')){case'user-agent':case'http-user-agent':return'User-Agent';case'referer':case'http-referer':case'http-referrer':return'Referer';default:return k;}}
  void dispose()=>_client.close();
}
