import 'package:flutter/material.dart' as material;

/// Arabic presentation layer used by the Arabic Debrify build.
/// It deliberately leaves URLs, provider names, technical identifiers and
/// values untouched while translating common UI/settings vocabulary.
String arabicUiText(String input) {
  if (input.trim().isEmpty) return input;
  const phrases = <String, String>{
    'Not connected': 'غير متصل',
    'Tap to connect': 'اضغط للاتصال',
    'Not configured': 'غير مُعد',
    'Connect Jackett or Prowlarr': 'اتصل بـ Jackett أو Prowlarr',
    'Check for new builds from GitHub releases': 'تحقق من الإصدارات الجديدة عبر GitHub',
    'Support Debrify': 'دعم Debrify',
    'Help fund development with a donation': 'ساهم في دعم تطوير التطبيق بالتبرع',
    'Real Debrid': 'Real-Debrid',
    'External Player': 'المشغل الخارجي',
    'Playback Settings': 'إعدادات التشغيل',
    'Subtitle Priority': 'أولوية الترجمة',
    'Home Page': 'الصفحة الرئيسية',
    'Home Page Settings': 'إعدادات الصفحة الرئيسية',
    'Discover Settings': 'إعدادات الاستكشاف',
    'App Theme': 'مظهر التطبيق',
    'Theme Lab': 'مختبر المظهر',
    'Theme Tokens': 'عناصر المظهر',
    'Detail Page': 'صفحة التفاصيل',
    'Player Controls': 'عناصر تحكم المشغل',
    'Quick Play': 'التشغيل السريع',
    'Profiles': 'الملفات الشخصية',
    'Profile Settings': 'إعدادات الملف الشخصي',
    'Tracking': 'التتبع',
    'Network': 'الشبكة',
    'Appearance': 'المظهر',
    'Notifications': 'الإشعارات',
    'Storage': 'التخزين',
    'Downloads': 'التنزيلات',
    'Playback': 'التشغيل',
    'Language': 'اللغة',
    'English': 'الإنجليزية',
    'Arabic': 'العربية',
    'Settings': 'الإعدادات',
    'General': 'عام',
    'Advanced': 'متقدم',
    'Account': 'الحساب',
    'Accounts': 'الحسابات',
    'Privacy': 'الخصوصية',
    'Security': 'الأمان',
    'About': 'حول التطبيق',
    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Close': 'إغلاق',
    'Done': 'تم',
    'Apply': 'تطبيق',
    'Reset': 'إعادة ضبط',
    'Default': 'افتراضي',
    'Enabled': 'مفعّل',
    'Disabled': 'معطّل',
    'On': 'تشغيل',
    'Off': 'إيقاف',
    'Enable': 'تفعيل',
    'Disable': 'تعطيل',
    'Add': 'إضافة',
    'Remove': 'إزالة',
    'Delete': 'حذف',
    'Edit': 'تعديل',
    'Rename': 'إعادة تسمية',
    'Import': 'استيراد',
    'Export': 'تصدير',
    'Backup': 'نسخة احتياطية',
    'Restore': 'استعادة',
    'Search': 'بحث',
    'Sort': 'ترتيب',
    'Filter': 'تصفية',
    'Refresh': 'تحديث',
    'Reload': 'إعادة تحميل',
    'Reset to default': 'إعادة إلى الإعداد الافتراضي',
    'Clear': 'مسح',
    'Clear all': 'مسح الكل',
    'Connected': 'متصل',
    'Connection': 'الاتصال',
    'Connection failed': 'فشل الاتصال',
    'Connection Details': 'تفاصيل الاتصال',
    'Server': 'الخادم',
    'Username': 'اسم المستخدم',
    'Password': 'كلمة المرور',
    'API Key': 'مفتاح API',
    'URL': 'الرابط',
    'Status': 'الحالة',
    'Last Connected': 'آخر اتصال',
    'Provider': 'المزوّد',
    'Providers': 'المزوّدون',
    'Real-Debrid': 'Real-Debrid',
    'Torbox': 'Torbox',
    'Premiumize': 'Premiumize',
    'AllDebrid': 'AllDebrid',
    'PikPak': 'PikPak',
    'WebDAV': 'WebDAV',
    'Trakt': 'Trakt',
    'Simkl': 'Simkl',
    'MDBList': 'MDBList',
    'IPTV': 'IPTV',
    'EPG': 'EPG',
    'Stremio': 'Stremio',
    'Addons': 'الإضافات',
    'Addon': 'إضافة',
    'Collections': 'المجموعات',
    'Movies': 'الأفلام',
    'Series': 'المسلسلات',
    'TV Shows': 'المسلسلات التلفزيونية',
    'Live TV': 'البث المباشر',
    'Player': 'المشغل',
    'Video': 'الفيديو',
    'Audio': 'الصوت',
    'Subtitles': 'الترجمات',
    'Subtitle': 'الترجمة',
    'Quality': 'الجودة',
    'Resolution': 'الدقة',
    'Playback speed': 'سرعة التشغيل',
    'Autoplay': 'التشغيل التلقائي',
    'Fullscreen': 'ملء الشاشة',
    'External': 'خارجي',
    'Internal': 'داخلي',
    'Preferred': 'المفضّل',
    'Theme': 'المظهر',
    'Dark': 'داكن',
    'Light': 'فاتح',
    'System': 'النظام',
    'Font': 'الخط',
    'Text': 'النص',
    'Brightness': 'السطوع',
    'Size': 'الحجم',
    'Style': 'النمط',
    'Layout': 'التخطيط',
    'Sidebar': 'الشريط الجانبي',
    'Home': 'الرئيسية',
    'Discover': 'استكشاف',
    'Profile': 'الملف الشخصي',
    'Remote': 'التحكم عن بُعد',
    'Android TV': 'Android TV',
    'Phone': 'الهاتف',
    'Desktop': 'سطح المكتب',
    'TV': 'التلفاز',
    'Screen': 'الشاشة',
    'Screen size': 'حجم الشاشة',
    'Render quality': 'جودة العرض',
    'Artwork quality': 'جودة الصور',
    'Animation': 'الحركة',
    'Launch animation': 'حركة التشغيل',
    'Player controls': 'عناصر تحكم المشغل',
    'Guide': 'الدليل',
    'Recording': 'التسجيل',
    'Recordings': 'التسجيلات',
    'Diagnostics': 'التشخيص',
    'Update': 'تحديث',
    'Updates': 'التحديثات',
    'Check for updates': 'التحقق من التحديثات',
    'Version': 'الإصدار',
    'About Debrify': 'حول Debrify',
    'Support': 'الدعم',
    'Donate': 'تبرع',
    'Warning': 'تحذير',
    'Error': 'خطأ',
    'Success': 'نجاح',
    'Failed': 'فشل',
    'Loading': 'جارٍ التحميل',
    'Please wait': 'يرجى الانتظار',
    'No results': 'لا توجد نتائج',
    'Not available': 'غير متاح',
    'Enabled by default': 'مفعّل افتراضيًا',
    'Use system language': 'استخدام لغة النظام',
  };
  final exact = phrases[input.trim()];
  if (exact != null && input == input.trim()) return exact;
  var result = input;
  final ordered = phrases.keys.toList()..sort((a, b) => b.length.compareTo(a.length));
  for (final key in ordered) {
    if (result.contains(key) && !RegExp(r'^[A-Za-z]+$').hasMatch(key)) {
      result = result.replaceAll(key, phrases[key]!);
    }
  }
  const words = <String, String>{
    'Settings':'الإعدادات','General':'عام','Advanced':'متقدم','Appearance':'المظهر','Language':'اللغة','English':'الإنجليزية','Arabic':'العربية',
    'Enable':'تفعيل','Disable':'تعطيل','Enabled':'مفعّل','Disabled':'معطّل','Default':'افتراضي','Save':'حفظ','Cancel':'إلغاء','Close':'إغلاق','Done':'تم','Apply':'تطبيق','Reset':'إعادة ضبط',
    'Add':'إضافة','Remove':'إزالة','Delete':'حذف','Edit':'تعديل','Import':'استيراد','Export':'تصدير','Backup':'نسخة احتياطية','Restore':'استعادة','Search':'بحث','Filter':'تصفية','Sort':'ترتيب','Refresh':'تحديث','Clear':'مسح',
    'Connection':'الاتصال','Connected':'متصل','Server':'الخادم','Username':'اسم المستخدم','Password':'كلمة المرور','Status':'الحالة','Provider':'المزوّد','Providers':'المزوّدون',
    'Player':'المشغل','Playback':'التشغيل','Video':'الفيديو','Audio':'الصوت','Subtitle':'الترجمة','Subtitles':'الترجمات','Quality':'الجودة','Resolution':'الدقة','Speed':'السرعة','Size':'الحجم','Style':'النمط','Layout':'التخطيط',
    'Home':'الرئيسية','Discover':'استكشاف','Profile':'الملف الشخصي','Profiles':'الملفات الشخصية','Account':'الحساب','Accounts':'الحسابات','Privacy':'الخصوصية','Security':'الأمان','Storage':'التخزين','Downloads':'التنزيلات','Network':'الشبكة','Notifications':'الإشعارات',
    'Theme':'المظهر','Dark':'داكن','Light':'فاتح','System':'النظام','Text':'النص','Brightness':'السطوع','Font':'الخط','Screen':'الشاشة','Phone':'الهاتف','Desktop':'سطح المكتب','Remote':'التحكم عن بُعد',
    'IPTV':'IPTV','EPG':'EPG','Addons':'الإضافات','Addon':'إضافة','Collections':'المجموعات','Movies':'الأفلام','Series':'المسلسلات','Live':'مباشر','TV':'التلفاز','Guide':'الدليل',
    'Update':'تحديث','Updates':'التحديثات','Version':'الإصدار','Support':'الدعم','Warning':'تحذير','Error':'خطأ','Success':'نجاح','Failed':'فشل','Loading':'جارٍ التحميل','Connected':'متصل','Offline':'غير متصل',
    'Automatic':'تلقائي','Automatically':'تلقائيًا','Manual':'يدوي','Custom':'مخصص','Preferred':'مفضّل','Current':'الحالي','New':'جديد','Old':'قديم','Show':'إظهار','Hide':'إخفاء','Choose':'اختيار','Select':'اختيار','Use':'استخدام','Enable':'تفعيل','Always':'دائمًا','Never':'أبدًا',
    'Start':'بدء','Stop':'إيقاف','Open':'فتح','Open':'فتح','Close':'إغلاق','Next':'التالي','Previous':'السابق','Back':'رجوع','Continue':'متابعة','Confirm':'تأكيد','Yes':'نعم','No':'لا',
  };
  result = result.replaceAllMapped(RegExp(r"\\b[A-Za-z][A-Za-z0-9_-]*\\b"), (m) => words[m.group(0)!] ?? m.group(0)!);
  return result;
}

class Text extends material.Text {
  const Text(
    String data, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.locale,
    super.softWrap,
    super.overflow,
    super.textScaler,
    super.maxLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.selectionColor,
  }) : super(arabicUiText(data));
}
